tasks:
  - init: ./mvnw clean install # Maven build (update if you use Gradle)
    command: ./mvnw spring-boot:run

ports:
  - port: 8080
    onOpen: open-preview # Automatically preview the app in Gitpod
